### PR TITLE
Update index.ja.mdx

### LINKED ISSUE #3148: Image link is broken
### Provide the exact quote of the error or issue

Image link of `InfiniteScrollArea` component is broken.
It is must be replace.

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/components/data-display/infinite-scroll-area#change-the-orientation

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### PR DESCRIPTION
**Pull request by 5AIPAVAN**
Closes #3148 

## Description

old image src in index.ja.mdx is broken 
so i changed it to "https://c4.wallpaperflare.com/wallpaper/946/34/413/anime-tengen-toppa-gurren-lagann-littner-yoko-thigh-highs-wallpaper-preview.jpg" to close this issue

## Current behavior (before updates)

before

## New behavior (after updates)

after

### CODE REVIEW

**Review by 108yen — CHANGES_REQUESTED** [review]
Thank you!
Can you fix en document as well?

**Comment by 5AIPAVAN** [comment]
> Thank you! Can you fix en document as well?

Done :-)

**Comment by 108yen** [comment]
@5AIPAVAN 
Sorry.
Can you replace url with this?
https://www.gurren-lagann.net/tv/images/kv.jpg

**Comment by 5AIPAVAN** [comment]
> @5AIPAVAN Sorry. Can you replace url with this? https://www.gurren-lagann.net/tv/images/kv.jpg

done :-)

**Review by 108yen — APPROVED** [review]
Thank you!

**Review by hirotomoyamada — APPROVED** [review]
Thanks!

**Pull request merged**
