### PR TITLE
feat: add display name for visually hidden elements

### LINKED ISSUE #2916: `displayName` is not set for the component of "@yamada-ui/visually-hidden"
script: component-display-name
package: @yamada-ui/visually-hidden

### Description
The component "@yamada-ui/visually-hidden" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

### PR DESCRIPTION
**Pull request by anushree0809**
Closes #2916

## Description

Added displayname and ui for visuallyhidden

## Current behavior (updates)

On the inspect tab, the component name will be visible

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by anushree0809** [comment]
Done, is there any other step needed?
Sorry for the slow steps, this is my first time contributing!

**Comment by illionillion** [comment]
> Done, is there any other step needed? Sorry for the slow steps, this is my first time contributing!

@anushree0809 
Thanks!!

Nothing in particular.

1. wait for CI to finish running
2. if the review requests a fix, fix it!
3. wait until it is approved and merged

**Comment by illionillion** [comment]
It's a forked repository, so it doesn't matter that the Vercel build is down.

**Review by illionillion — APPROVED** [review]
LGTM！！

**Review by hirotomoyamada — APPROVED** [review]

**Comment by anushree0809** [comment]
> It's a forked repository, so it doesn't matter that the Vercel build is down.

Okay,got it!

**Comment by hirotomoyamada** [comment]
Thanks!

**Pull request merged**
