### PR TITLE
fix: replace `ChevronIcon` in `Carousel` with `@yamada-ui/lucide`

### LINKED ISSUE #3528: Replace `ChevronIcon` in `Carousel` with `@yamada-ui/lucide`.
### Description

Replace `ChevronIcon` with `ChevronLeftIcon` and `ChevronRightIcon`.
Also, modify the `transform` property.

### Problem Statement/Justification

To unify with `@yamada-ui/lucide` and remove unnecessary icons.

### Proposed Solution or API

_No response_

### Alternatives

_No response_

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by illionillion**
Closes #3528  

## Description

Replace `ChevronIcon` with `ChevronLeftIcon` and `ChevronRightIcon`.
Also, modify the `transform` property.

### CODE REVIEW

**Review by nathanlao — APPROVED** [review]
I don't see any problems!

**Review by hirotomoyamada — CHANGES_REQUESTED** [review]
Insert `@yamada-ui/lucide` to `package.json`.

**Comment by illionillion** [comment]
@taroj1205 
Done it.

**Review by taroj1205 — APPROVED** [review]
LGTM Thanks!

**Review by hirotomoyamada — APPROVED** [review]

**Pull request merged**
