### PR TITLE
refactor(button-group): remove unnecessary marginBlockEnd property

### LINKED ISSUE #2670: Button frame style bug in ButtonGroup
### Which package has an issue?

@yamada-ui/react

### Package Version

1.5.0

### Description

The borders of the first and second buttons appear to overlap and be thicker when they are aligned vertically.

image

### Link to Reproduction

https://yamada-ui.com/ja/components/forms/button#グループ化する

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by bearone236**
Closes #2670 

## Description

The issue where Button components arranged vertically in a column had overlapping outlines has been resolved. By removing the `marginBlockEnd: -1px` property from the `button-group.tsx` file, the problem was fixed without disrupting the overall style and layout of the buttons.

### CODE REVIEW

**Review by illionillion — CHANGES_REQUESTED** [review]
Please make changeset.
`pnpm changeset`
@bearone236

**Review by illionillion — DISMISSED** [review]
LGTM

**Review by hirotomoyamada — COMMENTED** [review]
horizontal items have not been improved.

Perhaps the `-1px` approach needs to be revisited.

Updated

**Comment by bearone236** [comment]
> horizontal items have not been improved.
> 
> Perhaps the `-1px` approach needs to be revisited.

No outline overlap can be seen when the button groups are parallel.

スクリーンショット 2024-09-14 23 26 51

**Comment by hirotomoyamada** [comment]
No update, so we are closing.

**Pull request closed without merging**
