### PR TITLE
Add documentation for `FormatNumber` component

### LINKED ISSUE #3465: Add Documentation for `FormatNumber` component
### Subject

FormatNumber

### Description

I will add a documentation for `FormatNumber` component when the PR is merged.

### Are you willing to participate in creating this documentation page and create a pull request?

Yes

### PR DESCRIPTION
**Pull request by taroj1205**
Closes #3465

## Description

Added documentation for `format-number` component.

## Current behavior (updates)

N/A

## New behavior

N/A

## Is this a breaking change (Yes/No):

No

## Additional Information

N/A

### CODE REVIEW

**Comment by hirotomoyamada** [comment]
- The `theming.mdx` has not been added.
- The wording should match the rest of the document.
- Mention that the browser language will be automatically set.

**Comment by hirotomoyamada** [comment]
@taroj1205 

Hi, thanks for the PR.

- The `theming.mdx` has not been added.
- The wording should match the rest of the document.
- Mention that the browser language will be automatically set.

**Review by hirotomoyamada — CHANGES_REQUESTED** [review]
@taroj1205 

Hi, thanks for the PR.

- The `theming.mdx` has not been added.
- The `props.mdx` is not auto-generated. Please make sure it is auto-generated.
- The wording should match the rest of the document. Section titles and descriptions are different from other components.
- Mention that the browser language will be automatically set.
- Explain that you can set `locale` in `UIProvider`.

**Comment by taroj1205** [comment]
@hirotomoyamada I have applied your suggestions, please review again!

**Review by hirotomoyamada — APPROVED** [review]

**Pull request merged**
