### PR TITLE
Make the Calendar component headless

### LINKED ISSUE #1855: Make the `@yamada-ui/calendar` component headless
script: make-component-headless
package: @yamada-ui/calendar

### Description
Currently, the `@yamada-ui/calendar` component has minimal styles set within the component's source code.
We want to make this style transferable to the theme and make the component headless, enabling more flexible UI customization.

### Problem Statement/Justification
By making the `@yamada-ui/calendar` component headless, we can achieve more flexible styling tailored to the project.

### Proposed Solution or API
The styles within the component are mostly defined by `css: CSSUIObject` and set to a prop named `__css`. We will transfer these styles to the `packages/theme/src/components`.

The code below is just an example and not the actual code.

`packages/components/input/src/input-group.tsx`
```diff
const css: CSSUIObject = {
- width: "100%",
- display: "flex",
- position: "relative",
  ...styles.container,
}
```

`packages/theme/src/components/input.ts`
```diff
baseStyle: {
  container: {
+   width: "100%",
+   display: "flex",
+   position: "relative",
  },
  field: {
    width: "100%",
    minWidth: 0,
    outline: 0,
    position: "relative",
    appearance: "none",
    transitionProperty: "common",
    transitionDuration: "normal",
    _disabled: {
      opacity: 0.4,
      cursor: "not-allowed",
    },
  },
  element: {
    color: ["blackAlpha.600", "whiteAlpha.700"],
  },
},
```

> [!TIP]
>
> In cases where the styles within the component are dynamically changed, there may be instances where it is not possible to transfer the styles to the `theme`.
> In such cases, it needs to be discussed in this issue. Please feel free to send comments to this issue.

### Additional Information
The `@yamada-ui/calendar` component exists in `packages/components/calendar/src`. You need to check all the components in this folder and if they contain styles internally, you need to modify them.

This change could have a significant impact on projects using Yamada UI, so we will work on it within the scope of `v2.0`.
Please create the branch for working on this issue from the remote branch `v2.0`, and direct your pull requests to the `v2.0` branch as well.

Please select `major` for the changeset and create a pull request.

### PR DESCRIPTION
**Pull request by Hiroto1224**
Closes #1855 

## Description

Make the component headless

## Is this a breaking change (Yes/No):

No.

### CODE REVIEW

**Comment by Hiroto1224** [comment]
@hirotomoyamada 
I couldn’t determine the target location for migrating this CSSUIObject because there was no reference like ‘…styles.container’. In this case, where should it be correctly migrated?

https://github.com/yamada-ui/yamada-ui/blob/aaf8adbe319745679dff5b21647798e4507eaed9/packages/components/calendar/src/range-date-picker.tsx#L273-L277

**Comment by hirotomoyamada** [comment]
@Hiroto1224 

Hi, thanks for the PR.

In that case, you don't need to move.

**Review by 108yen — CHANGES_REQUESTED** [review]
Only one `changeset` file is needed.

**Comment by koralle** [comment]
@Hiroto1224 

Since there was no response for a week, we will handle it here.

**Comment by hirotomoyamada** [comment]
@108yen @Haru-0001 @nakayan5 @ayanami77 

Please re-reviews.

**Review by Haru-0001 — APPROVED** [review]

**Review by illionillion — APPROVED** [review]

**Pull request merged**
