### PR TITLE
docs: Rename Divider to Separator

### LINKED ISSUE #3292: Rename `Divider` to `Separator`
### Description

package: @yamada-ui/layouts

Enhancement of `<Divider />`

### Problem Statement/Justification

Renaming the component  `<Divider />`  to `<Separator />`
- Add `@deprecated` in v1

### Proposed Solution or API

_No response_

### Alternatives

_No response_

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

### Additional Information

Create a working branch from v2.0 please

### PR DESCRIPTION
**Pull request by tskxz**
Closes #3292 

As mentioned in pull request #3300 , I created a separate PR about documentation.

I renamed Divider to Separator in docs folder. I would like to know if I still must generate a changelog

### CODE REVIEW

**Review by mei28 — APPROVED** [review]
@tskxz 
Thank you for your PRs! They look great – nice work!

For documentation work like this, there’s no need to write a changeset, so everything is good as it is.

**Comment by mei28** [comment]
I think it would be best to merge this PR after #3300 has been merged, or at the same time.

**Review by hirotomoyamada — CHANGES_REQUESTED** [review]
The following files are automatically generated and should not be included in the change.

- `docs/contents/components/**/props.ja.mdx`
- `docs/contents/components/**/props.mdx`
- `docs/contents/components/**/theming.ja.mdx`
- `docs/contents/components/**/theming.mdx`
- `docs/i18n/content.en.json`
- `docs/i18n/content.ja.json`

**Comment by hirotomoyamada** [comment]
@tskxz

Hi, Thanks for the PR!

A week has passed since this PR was created, so maintainers will be joining this PR.

**Comment by hirotomoyamada** [comment]
@tskxz 

Sorry, fixed #3676

**Pull request closed without merging**
