### PR TITLE
Thematize `Icon` component

### LINKED ISSUE #2208: Thematize `Icon` component
### Description

Yamada UI components are tied to a theme. However, the `Icon` component does not have a theme.

### Problem Statement/Justification

Themes have `defaultProps`, which can be utilized to share `props` throughout the project. However, the `Icon` component does not have a theme, so it cannot take advantage of them.

### Proposed Solution or API

_No response_

### Alternatives

_No response_

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by cidkumagai**
Closes #2208 

## Description

Thematize `Icon` component

### CODE REVIEW

**Review by 108yen — COMMENTED** [review]
Check quality.

**Comment by cidkumagai** [comment]
@108yen 
I've tried to fix it, please review.

**Review by 108yen — COMMENTED** [review]
quality is still failing.

**Comment by cidkumagai** [comment]
@108yen 
```
Error: packages/components/loading/src/loading-provider.tsx(411,20): error TS2322: Type 'UIValue<number | "12" | "auto" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "14" | (string & {}) | "px" | "min" | "max" | "sm" | "md" | "lg" | "xl" | "2xl" | "2xs" | "xs" | "3xl" | ... 50 more ... | "min-intrinsic">' is not assignable to type '(UIValue<string> & UIValue<number | "small" | (string & {}) | "sm" | "md" | "lg" | "xl" | "2xl" | "2xs" | "xs" | "3xl" | "4xl" | "5xl" | "6xl" | "7xl" | "8xl" | "9xl" | "medium" | ... 13 more ... | "smaller">) | undefined'.
Error: packages/components/loading/src/loading-provider.tsx(460,20): error TS2322: Type 'UIValue<number | "12" | "auto" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "[14](https://github.com/yamada-ui/yamada-ui/actions/runs/10016849752/job/27690307570?pr=2309#step:6:15)" | (string & {}) | "px" | "min" | "max" | "sm" | "md" | "lg" | "xl" | "2xl" | "2xs" | "xs" | "3xl" | ... 50 more ... | "min-intrinsic">' is not assignable to type '(UIValue<string> & UIValue<number | "small" | (string & {}) | "sm" | "md" | "lg" | "xl" | "2xl" | "2xs" | "xs" | "3xl" | "4xl" | "5xl" | "6xl" | "7xl" | "8xl" | "9xl" | "medium" | ... 13 more ... | "smaller">) | undefined'.
Error: packages/components/loading/src/loading-provider.tsx(506,18): error TS2322: Type 'UIValue<number | "12" | "auto" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "14" | (string & {}) | "px" | "min" | "max" | "sm" | "md" | "lg" | "xl" | "2xl" | "2xs" | "xs" | "3xl" | ... 50 more ... | "min-intrinsic">' is not assignable to type '(UIValue<string> & UIValue<number | "small" | (string & {}) | "sm" | "md" | "lg" | "xl" | "2xl" | "2xs" | "xs" | "3xl" | "4xl" | "5xl" | "6xl" | "7xl" | "8xl" | "9xl" | "medium" | ... 13 more ... | "smaller">) | undefined'.
```

It doesn't seem relevant to this issue, but do we need to fix?

**Comment by 108yen** [comment]
@cidkumagai 
It seems to be using `iconProps` with `Loading`.
`loading.tsx`
```ts
export type LoadingProps = IconProps &
  Pick<ThemeProps<"Loading">, "colorScheme"> &
  LoadingOptions
```

**Comment by cidkumagai** [comment]
@108yen 
I see. Thank you very much.
I'll fix it.

**Comment by cidkumagai** [comment]
@108yen 
Sorry, I don't know how to fix it, can you please tell me?

**Comment by 108yen** [comment]
@cidkumagai 
I am not sure if this policy is correct, but this will eliminate the error.
```tsx
export type IconProps = Omit<SVGAttributes<SVGElement>, keyof UIProps> &
  Omit<ThemeProps<"Icon">, "size"> &
  UIProps &
  IconOptions
```

**Comment by cidkumagai** [comment]
@108yen 
Thank you!!
Correction.

**Review by 108yen — APPROVED** [review]

**Review by hirotomoyamada — APPROVED** [review]

**Pull request merged**
