### PR TITLE
fix: displayName is not set for the component of "@yamada-ui/progress"

### LINKED ISSUE #2893: `displayName` is not set for the component of "@yamada-ui/progress"
script: component-display-name
package: @yamada-ui/progress

### Description
The component "@yamada-ui/progress" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

### PR DESCRIPTION
**Pull request by mei28**
Closes #2893

### CODE REVIEW

**Review by illionillion — CHANGES_REQUESTED** [review]
@mei28 

Thank for PR!!
All components of PROGRESS should be modified in the same way.

**Comment by mei28** [comment]
Thank you for your review. I believed I had applied all components of PROGRESS under packages/components/progress/src, but is there still something missing? If I have misunderstood anything, please let me know.

**Comment by illionillion** [comment]
> Thank you for your review. I believed I had applied all components of PROGRESS under packages/components/progress/src, but is there still something missing? If I have misunderstood anything, please let me know.

@mei28 

- `Shape`
- `Circle`
- `CircleProgressLabel`
- `ProgressFilledTrack`

These are also components.

**Comment by mei28** [comment]
I have added the remaining components.

However, I failed the Prettier check in CI. Could you please help me understand how to resolve it?

**Review by Itsuki54 — CHANGES_REQUESTED** [review]
@mei28 
Thank for PR!!

Please correct them.

**Review by Itsuki54 — APPROVED** [review]
@mei28
Thank for PR!!

LGTM

**Review by hirotomoyamada — APPROVED** [review]

**Review by illionillion — APPROVED** [review]

**Pull request merged**
