### PR TITLE
fix(docs): Added `import type GatsbyBrowser` to `gatsby-browser.tsx`

### LINKED ISSUE #2742: The gatsby-browser.tsx example on the `Getting Started with Gatsby' page is inappropriate
### Provide the exact quote of the error or issue

If you create "gatsby-browser.tsx" according to the "Getting Started with Gatsby" page, you will get an error because the "GatsbyBrowser" type is not imported.

👎 
image

You need to modify it to import "GatsbyBrowser".
👍 
image

### Does the docs page already exist? Please link to it.

https://yamada-ui.com/getting-started/frameworks/gatsby

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### PR DESCRIPTION
**Pull request by fffk10**
Closes #2742

### CODE REVIEW

**Review by kurakke — APPROVED** [review]

**Review by hirotomoyamada — COMMENTED** [review]
The Japanese page also needs to be corrected.

**Comment by fffk10** [comment]
@hirotomoyamada 

Thx, I fixed it

**Comment by hirotomoyamada** [comment]
@fffk10 

Hi, have you forgotten to push?

**Comment by fffk10** [comment]
@hirotomoyamada 

sorry,I fix yet.
I wanted to tell them, "I'll fix it."

**Comment by fffk10** [comment]
@hirotomoyamada 

I fixed it.
Please rereview.

179e0b05c07bda7526c72a36506ff61f5b430d1b

**Review by hirotomoyamada — APPROVED** [review]

**Pull request merged**
