### PR TITLE
Feat set display name and UI for transitions

### LINKED ISSUE #2914: `displayName` is not set for the component of "@yamada-ui/transitions"
script: component-display-name
package: @yamada-ui/transitions

### Description
The component "@yamada-ui/transitions" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

### PR DESCRIPTION
**Pull request by 0xtkey256**
Closes #2914

## Description

Set `displayName` for the `@yamada-ui/transitions` component to make debugging easier.
This change improves the ability to identify the component name in development tools.

## Current behavior (updates)

Currently, `displayName` is not set for the `@yamada-ui/transitions` component, making it difficult to identify the component in debugging tools like React Developer Tools.

## New behavior

With `displayName` set, the `@yamada-ui/transitions` component now displays its name correctly in debugging tools like React Developer Tools, making it easier for developers to identify and debug the component.

## Is this a breaking change (Yes/No):

No.

## Additional Information

Nada.

### CODE REVIEW

**Comment by 0xtkey256** [comment]
@hirotomoyamada & @cidkumagai 
I've created a PR.
Please review it, and I appreciate your review.

**Comment by cidkumagai** [comment]
@0xtkey256 
I think `ScaleFade` also needs to be addressed, so could you please handle it as well?

**Comment by 0xtkey256** [comment]
> @0xtkey256 I think `ScaleFade` also needs to be addressed, so could you please handle it as well?

Yes, I somehow discarded from the previous commit. I've added the `ScaleFade`. Thanks for bringing it to my attention.

**Review by cidkumagai — APPROVED** [review]
LGTM!

**Pull request merged**
