### PR TITLE
test: add default value test pattern

### LINKED ISSUE #1022: Enhance Test Coverage for `@yamada-ui/autocomplete`
package: @yamada-ui/autocomplete

### Description
`@yamada-ui/autocomplete` has a test coverage of less than 80%. We will enhance it to above 80%.

### Target files
- [packages/components/autocomplete/src/autocomplete-icon.tsx](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/autocomplete/src/autocomplete-icon.tsx)
  - [L32](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/autocomplete/src/autocomplete-icon.tsx#L32)
  - [L61](https://app.codecov.io/gh/yamada-ui/yamada-ui/blob/main/packages/components/autocomplete/src/autocomplete-icon.tsx#L61)

### Problem Statement/Justification
Testing is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all tests, if there are too many lines to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

### PR DESCRIPTION
**Pull request by suzukisan22**
Closes #1022

## Description

- add default value test pattern

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by KenyaMasuko — COMMENTED** [review]
I commented out the defaultValue and removed it, and the tests still pass. Is this the correct behavior?

**Comment by suzukisan22** [comment]
yes, reason why i added default values is to show AutocompleteClearIcon button.

**Comment by suzukisan22** [comment]
but i'll add more expectation

**Comment by 108yen** [comment]
@suzukisan22 
Isn't this enough?
```tsx
    test("have default value", async () => {
      render(
        <MultiAutocomplete
          placeholder="Select Option"
          defaultValue={["option1", "option2"]}
        >
          <AutocompleteOption value="option1">option1</AutocompleteOption>
          <AutocompleteOption value="option2">option2</AutocompleteOption>
          <AutocompleteOption value="option3">option3</AutocompleteOption>
        </MultiAutocomplete>,
      )

      expect(screen.getByText("option1,")).toBeInTheDocument()
    })
```

**Review by hirotomoyamada — DISMISSED** [review]

**Review by 108yen — APPROVED** [review]

**Pull request merged**
