### PR TITLE
Added theme support and refactored code

### LINKED ISSUE #2210: Thematize `FileButton` component
### Description

Yamada UI components are tied to a theme. However, the `FileButton` component does not have a theme.

### Problem Statement/Justification

Themes have `defaultProps`, which can be utilized to share `props` throughout the project. However, the `FileButton` component does not have a theme, so it cannot take advantage of them.

### Proposed Solution or API

_No response_

### Alternatives

_No response_

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #2210

## Description

Added theme support and refactored code.

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by 108yen — COMMENTED** [review]
The components are displayed differently in the storybook, please check to see if this is a problem.

**Comment by hirotomoyamada** [comment]
@108yen 

Where is the Storybook?
What is the page?

**Comment by 108yen** [comment]
@hirotomoyamada 
Please check FileButton/withSize, withColorScheme, withVariant.

**Comment by hirotomoyamada** [comment]
@108yen 

Fixed.

**Review by 108yen — APPROVED** [review]

**Pull request merged**
