### PR TITLE
Update ref forwarding and prop types

### LINKED ISSUE #3192: The omission of `Pagination` is clickable.
### Which package has an issue?

@yamada-ui/react

### Package Version

1.5.4

### Description

The omission of `Pagination` is clickable. Apparently, the styling is also out of whack.

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #3192

## Description

Update ref forwarding and prop types.

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by taroj1205 — COMMENTED** [review]
Hi thanks for the PR!

The tests seem to be failing, could you check them?

**Comment by hirotomoyamada** [comment]
@taroj1205 

Fixed.

**Comment by hirotomoyamada** [comment]
@taroj1205 

Please reviews.

**Review by taroj1205 — APPROVED** [review]
Thanks! LGTM!

**Pull request merged**
