### PR TITLE
Add `YearPicker` component

### LINKED ISSUE #1536: Add `YearPicker`
### Description

A component that allows you to select the year.

### Problem Statement/Justification

Currently, there is a component that allows you to select the date and month, but there is no component that allows you to select just the year.

### Proposed Solution or API

_No response_

### Alternatives

_No response_

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

Yes

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #1536

## Description

Add `YearPicker` component.

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by KenyaMasuko — COMMENTED** [review]
[ask]
When the Year Picker is set to 'isReadonly' and a value is assigned, the clear button becomes clickable. Is this the correct behavior?
image

**Comment by hirotomoyamada** [comment]
@KenyaMasuko 

> [ask] When the Year Picker is set to 'isReadonly' and a value is assigned, the clear button becomes clickable. Is this the correct behavior? image

This is a bug.
However, this bug occurs not only with `YearPicker` but also with `MonthPicker` and `MultiSelect`. I will try to fix this bug in another issue.

**Comment by hirotomoyamada** [comment]
@KenyaMasuko 

> @KenyaMasuko
> 
> > [ask] When the Year Picker is set to 'isReadonly' and a value is assigned, the clear button becomes clickable. Is this the correct behavior? image
> 
> This is a bug. However, this bug occurs not only with `YearPicker` but also with `MonthPicker` and `MultiSelect`. I will try to fix this bug in another issue.

Created issue.

#1582

**Review by KenyaMasuko — APPROVED** [review]
ok, thanks!

**Pull request merged**
