### PR TITLE
Added `DataList` component

### LINKED ISSUE #3215: Add `DataList` component
### Description

Used to display a list of similar data items.

- https://www.chakra-ui.com/docs/components/data-list

### Problem Statement/Justification

It is used frequently in applications and should be provided by default in the Yamada UI.

### Proposed Solution or API

_No response_

### Alternatives

_No response_

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

Yes

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #3215

Added `DataList` component.

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by taroj1205 — DISMISSED** [review]
LGTM Thanks!

**Comment by hirotomoyamada** [comment]
@taroj1205 

Please re-reviews.

**Comment by taroj1205** [comment]
> @taroj1205
> 
> Please re-reviews.

Hi @hirotomoyamada, the test is still failing.

**Comment by hirotomoyamada** [comment]
@taroj1205 

Fixed.

**Review by taroj1205 — APPROVED** [review]
LGTM Thanks!

**Pull request merged**
