### PR TITLE
refactor: make the skeleton component headless

### PR DESCRIPTION
**Pull request by hiroking777**
Closes # #1901

## Description

make the skeleton component headless

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by hiroking777** [comment]
@hirotomoyamada 
Excuse me, I think there are dynamic stylings in skeleton component.
So I switched styles to theme those are not using dynamic styling, and leave styles those are using it.
The leaved styles are "width", and "height", and I think they are not involved to theme directly.
Is there any problems?

**Review by Hayato1031 — APPROVED** [review]
LGTM

**Review by illionillion — APPROVED** [review]

**Review by 108yen — APPROVED** [review]

**Comment by hirotomoyamada** [comment]
@hiroking777 

Hi, thanks for the PR!

It's not a problem:)

**Comment by hirotomoyamada** [comment]
Thanks!

**Pull request merged**
