### PR TITLE
Fixed use-select & use-autocomplete logic

### LINKED ISSUE #2179: SelectのdefaultValueが無視されてしまう
### どのパッケージに問題がありますか？

@yamada-ui/react

### パッケージのバージョン

1.4.2

### 概要

ドキュメントのSelectの初期値を設定するコードをそのまま貼り付けると、選択状態は正しいものの、
UIの見た目に初期値が反映されていません。

```js
<Select placeholder="キャラクターを選択" defaultValue="ベジータ">
  <Option value="孫悟空">孫悟空</Option>
  <Option value="ベジータ">ベジータ</Option>
  <Option value="フリーザ">フリーザ</Option>
</Select>
```

image
image

### 再現へのリンク

https://codesandbox.io/p/sandbox/yamada-ui-react-cql27v?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxvkh9dw0006336mhf8bkd5n%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxvkh9dv0002336mh2wfj5cp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxvkh9dv0003336mnh4ig2ml%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxvkh9dv0005336mui0habzm%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxvkh9dv0002336mh2wfj5cp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvkh9dv0001336majwpuiqs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clxvkh9dv0002336mh2wfj5cp%2522%252C%2522activeTabId%2522%253A%2522clxvkh9dv0001336majwpuiqs%2522%257D%252C%2522clxvkh9dv0005336mui0habzm%2522%253A%257B%2522id%2522%253A%2522clxvkh9dv0005336mui0habzm%2522%252C%2522activeTabId%2522%253A%2522clxvkj4mb000y336mk3ber39i%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxvkh9dv0004336mh1iu4hom%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clxvkj4mb000y336mk3ber39i%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxvkh9dv0003336mnh4ig2ml%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxvkh9dv0003336mnh4ig2ml%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 再現手順

1. Sandboxをブラウザで開くか、ドキュメントのSelectのdefaultValueの説明のコードを貼り付けます。
2.  defaultValueで指定している「ベジータ」が表示されているはずが、placeholderが表示されています。
3.  Selectをクリックすると、内部の選択状態ではdefaultValueが反映されているようです。

### ブラウザ

Chrome

### OS

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### まさか、問題の修正方法をご存知ですか？

いいえ

### この問題の修正に参加し、修正を含むプルリクエストを作成しますか？

いいえ

### 追加情報

_No response_

### PR DESCRIPTION
**Pull request by Shunii85**
Closes #2179 

## Description
Add if statements to use-select.ts and use-autocomplete.ts.

## Is this a breaking change (Yes/No):
No

### CODE REVIEW

**Review by zonoryo17 — COMMENTED** [review]
It appears that this modification will require changes to the test as well.

Passing an empty string ("") to the following test seems to produce the expected results.

```tsx
await waitFor(() => expect(input).toHaveValue("option1"))

await user.keyboard("{Backspace>}")
await waitFor(() => expect(input).not.toHaveValue("")))
```

https://github.com/yamada-ui/yamada-ui/pull/2220/files#file-packages-components-autocomplete-tests-autocomplete-test-tsx-L521-L524

**Comment by Shunii85** [comment]
@zonoryo17 
Thank you!

**Review by zonoryo17 — DISMISSED** [review]
LGTM👾

**Comment by hirotomoyamada** [comment]
@Shunii85 @zonoryo17 @nakayan5 

I have corrected it.Please review again.

**Comment by koralle** [comment]
@hirotomoyamada @Shunii85 
I just realized, isn't there a missing test case to assert the initial state of the `Select` component when the `defaultValue` prop is set?

**Review by koralle — APPROVED** [review]

**Review by hirotomoyamada — APPROVED** [review]

**Pull request merged**
