### PR TITLE
Add a `muted` color semantic.

### LINKED ISSUE #2525: Add `muted` to the semantic token
### Description

Add `muted` to the semantic token.

### Problem Statement/Justification

We use the `muted` token on the Yamada UI documentation site and Yamada Colors to set colors for text and other elements that we don't want to stand out.

I think there is a demand for that, so I will implement it on the Yamada UI side as well.

### Proposed Solution or API

_No response_

### Alternatives

_No response_

### Are you willing to participate in implementing this feature and create a pull request include the implementation?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Shunii85**
Closes #2525 

## Description
Add a `muted` color semantic to yamada-ui. Additionally, add a story documentation.

### CODE REVIEW

**Review by haru-036 — APPROVED** [review]

**Comment by hirotomoyamada** [comment]
@Shunii85 

Hi, thanks for the PR.

This fix was planned to be a feature to be added based on #2524.

But let me think about this for a moment, because I also think that it would be good to release this one first.

**Comment by hirotomoyamada** [comment]
@Shunii85 

Hi, The documentation site theme also needs to be updated.

Also, both Yamada Colors and Yamada Components need to be updated after this PR is merged.

**Comment by Shunii85** [comment]
Hi, @hirotomoyamada 
Is there anything I still need to do for this PR ? The documentation etc.

**Comment by haru-036** [comment]
Hi,  @Shunii85 
I think `muted` is defined separately in the semantics of the document and should be removed

**Comment by hirotomoyamada** [comment]
@Shunii85 

`docs/theme/semantics.ts`

This needs to be corrected here.

**Review by hirotomoyamada — APPROVED** [review]

**Pull request merged**
