### PR TITLE
fix: a11y for pin-input

### LINKED ISSUE #1246: Enhance a11y for `PinInput`
path: stories/components/forms/pin-input.stories.tsx

### Description
1 accessibility violation was found in the `PinInput`.

#### [isReadonly](https://yamada-ui.github.io/yamada-ui/?path=/story/components-forms-pininput--is-readonly)

Expected the HTML found at $('section > .css-nqtsdw.ui-pin-input[aria-readonly="true"]') to have no violations:
    <div class="ui-pin-input css-nqtsdw" readonly="" aria-readonly="true" data-readonly="">

    Received:
    Elements must only use supported ARIA attributes (aria-allowed-attr)

    Fix all of the following:
      ARIA attribute is not allowed: aria-readonly="true"

    You can find more information on this issue here: 
    https://dequeuniversity.com/rules/axe/4.9/aria-allowed-attr?application=axeAPI

Expected the HTML found at $('.ui-form__control > .css-nqtsdw.ui-pin-input[aria-readonly="true"]') to have no violations:
    <div class="ui-pin-input css-nqtsdw" readonly="" aria-readonly="true" data-readonly="">

    Received:
    Elements must only use supported ARIA attributes (aria-allowed-attr)

    Fix all of the following:
      ARIA attribute is not allowed: aria-readonly="true"

    You can find more information on this issue here: 
    https://dequeuniversity.com/rules/axe/4.9/aria-allowed-attr?application=axeAPI

### Problem Statement/Justification
A11y is essential to ensure quality when operating a package.

### Additional Information
While it's ideal to cover all jobs, if there are too many jobs to work on, please create a PR within your capacity.
Any deficiencies not covered by the PR will be automatically created as issues.

### PR DESCRIPTION
**Pull request by GensIto**
Closes #1246 

## Description

The cause is that the div has aria-readonly="true".
[MDN](https://developer.mozilla.org/ja/docs/Web/API/Element/ariaReadOnly)
aria-readonly can be used only for input and textarea

## Current behavior (updates)

Improvement of a11y
a11y error is being displayed in storybook

## New behavior

Pass rest to cloneChildren instead of fulfilling rest to div.
I no longer see the a11y error in the storybook.

スクリーンショット 2024-04-29 10 57 44

## Is this a breaking change (Yes/No):
No

## Additional Information

### CODE REVIEW

**Comment by imaimai17468** [comment]
@GensIto 
It is dangerous to pass all rests as props of a separate component, as it may change the original behavior as well.
It is recommended to simply remove aria-readonly from rest.

**Comment by GensIto** [comment]
@imaimai17468 
I have made a modification to remove aria-readonly from rest, is this the intended modification?

**Review by imaimai17468 — APPROVED** [review]
Sorry for the delay in reviewing this.
LGTM!

**Comment by hirotomoyamada** [comment]
Thanks!

**Pull request merged**
