### PR TITLE
Change rating classname `ui-rating__item__icon` to `ui-rating__item-icon`

### LINKED ISSUE #1589: Fix class name in `Rating`
### Which package has an issue?

@yamada-ui/react

### Package Version

1.3.9

### Description

Corrected the following class names according to BEM

- `ui-rating__item__icon`
  - fix to `ui-rating__item-icon`

Create the changeset with `major`.
Please derive a new branch from the `v2.0` branch and create a pull request for the `v2.0` branch, not the `main` branch, as we plan to release the product in v2.0.0.

Fix the test code if necessary.

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by cidkumagai**
Closes #1589 

## Description

> Add a brief description

## Current behavior (updates)

> Please describe the current behavior that you are modifying

## New behavior

> Please describe the behavior or changes this PR adds

### CODE REVIEW

**Comment by hoshico** [comment]
@cidkumagai 
Thank you for your PR!
Initial letters should be capitalized in changesets

**Comment by cidkumagai** [comment]
@hoshico 
I did dix now. please re-review!

**Review by hoshico — APPROVED** [review]
LGTM

**Review by hirotomoyamada — APPROVED** [review]

**Review by hirotomoyamada — APPROVED** [review]

**Comment by hirotomoyamada** [comment]
Thanks!

**Pull request merged**
