### PR TITLE
refactor: Deprecated props are being used in the example pages. 

### PR DESCRIPTION
**Pull request by mk0812**
Closes https://github.com/yamada-ui/yamada-ui/issues/2494

## Description

- As the subject suggests, I have changed the deprecated size prop in the Icon component to fontSize.
  - reference: [Corresponding code](https://github.com/yamada-ui/yamada-ui/blob/1473921f8aeb4e2040d0337aee3b101e78884749/packages/components/icon/src/icon.tsx#L17C6-L24)

## Current behavior (updates)

- None

## New behavior

- None

## Is this a breaking change (Yes/No):

- No

## Additional Information
- None

### CODE REVIEW

**Review by taroj1205 — CHANGES_REQUESTED** [review]
Hi @mk0812 thanks for your PR!

There are more components in examples that use the deprecated prop `size`.
Please change these too.

**Comment by mk0812** [comment]
@taroj1205 
Sorry, I initially thought I only needed to update the files under examples/mail, but should I be handling everything under the examples directory? 

I focused only on mail because the issue description specifically mentioned mail.

> Does the docs page already exist? Please link to it.
https://yamada-ui.com/examples/mail

**Comment by taroj1205** [comment]
> @taroj1205 Sorry, I initially thought I only needed to update the files under examples/mail, but should I be handling everything under the examples directory?
> 
> I focused only on mail because the issue description specifically mentioned mail.
> 
> > Does the docs page already exist? Please link to it.
> > [yamada-ui.com/examples/mail](https://yamada-ui.com/examples/mail)

@mk0812 
Yes please update all the files under the examples directory. Thanks for your understanding.

**Comment by mk0812** [comment]
Sure, I’ll take care of it!

**Comment by mk0812** [comment]
@taroj1205 
I addressed it in the following commit.(commit
https://github.com/yamada-ui/yamada-ui/pull/2509/commits/dc89382bf98da3ff712fcaf14049d03760c6d537

How I investigated:
I searched using grep under the examples directory as follows.

```sh
$ grep -r '<Icon.*size=' ./docs/pages/examples
```

**Review by taroj1205 — CHANGES_REQUESTED** [review]
Please also fix the following files:
- https://github.com/yamada-ui/yamada-ui/blob/dff23bc2094f64d281a76a467c7c343dc643c2fb/docs/pages/examples/cards/notification-card.tsx

**Comment by mk0812** [comment]
@taroj1205 
Sorry, I addressed it in the following commit.

https://github.com/yamada-ui/yamada-ui/pull/2509/commits/ccec39b08c5e5e37a3601fdbf415696b52f5ba2f

**Review by taroj1205 — APPROVED** [review]
LGTM Thanks!

**Review by hirotomoyamada — APPROVED** [review]

**Comment by hirotomoyamada** [comment]
Thanks!

**Pull request merged**
