### PR TITLE
Updated git repo url and README.md

### LINKED ISSUE #2641: The repository URL for `package.json` is incorrect
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.9

### Description

The repository URL for `package.json` is incorrect.

`"url": "https://github.com/yamada-ui/yamada-ui"` instead of `"url": "git+https://github.com/yamada-ui/yamada-ui"`.

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

_No response_

### LINKED ISSUE #2642: The documentation describes installation using bun, but the README.md does not
### Which package has an issue?

@yamada-ui/react

### Package Version

1.4.9

### Description

The documentation describes installation using bun, but the README.md does not.

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iPadOS
- [ ] iOS
- [ ] Android

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

Yes

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by hirotomoyamada**
Closes #2642
Closes #2641

## Description

Updated git repo url and README.md.

## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Review by hinataOhyama — APPROVED** [review]

**Review by odendayoko — CHANGES_REQUESTED** [review]
@hirotomoyamada 
Could you please extend the same changes to plop, `MarkDown` documentation, and StoryBook as well?

**Comment by hirotomoyamada** [comment]
@odendayoko 

> Could you please extend the same changes to plop, MarkDown documentation, and StoryBook as well?

Fixed:)

**Review by odendayoko — CHANGES_REQUESTED** [review]
@hirotomoyamada 
Could you also extend these changes to the following template files:

1. plop/component/package/README.md.hbs
2. plop/component/package-multi/README.md.hbs
3. plop/hook/package/README.md.hbs

**Comment by hirotomoyamada** [comment]
@odendayoko 

Fixed.

**Review by odendayoko — APPROVED** [review]
@hirotomoyamada 
Thank you!! LGTM

**Pull request merged**
