### PR TITLE
fix(textarea): fix bug where resize was not triggered

### LINKED ISSUE #827: The `autosize` function of the `Textarea` component does not work when the `reset` of the `React Hook Form` is executed.
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.6

### Description

When running a `Textarea` component on a `React Hook Form`, `autosize` does not work when `reset` is executed.

https://github.com/hirotomoyamada/yamada-ui/assets/60034520/c4e74b12-66d0-41e5-b8c5-0bf78e252dd5

```tsx
export const reactHookForm: Story = () => {
  type Data = { textarea: string }

  const {
    register,
    handleSubmit,
    watch,
    reset,
    formState: { errors },
  } = useForm<Data>()

  const onSubmit: SubmitHandler<Data> = (data) => console.log("submit:", data)

  console.log("watch:", watch())

  return (
    <VStack as="form" onSubmit={handleSubmit(onSubmit)}>
      <FormControl
        isInvalid={!!errors.textarea}
        label="Feedback"
        errorMessage={errors.textarea?.message}
      >
        <Textarea
          autosize
          placeholder="your feedback"
          {...register("textarea", {
            required: { value: true, message: "This is required." },
          })}
        />
      </FormControl>

      <Button type="button" alignSelf="flex-end" onClick={() => reset()}>
        Reset
      </Button>
      <Button type="submit" alignSelf="flex-end">
        Submit
      </Button>
    </VStack>
  )
}
```

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

It can be improved by adding the following `useSafeLayoutEffect` program in the `Textarea` component of `textarea.tsx`.

```tsx
useSafeLayoutEffect(() => {
  if (!isBrowser || !autosize) return
  resizeTextarea()
}, [textareaRef.current?.value])
```

https://github.com/hirotomoyamada/yamada-ui/assets/60034520/73fcc181-f8de-4a9c-8d83-2cd12e8ee419

### PR DESCRIPTION
**Pull request by 108yen**
Closes #827

## Description

Fixed autosize when a value is changed by manipulating a ref, like reset() in react-hook-form.
And added functionality to trigger resize.

## Current behavior (updates)

Not resize when reset() in react-hook-form

## New behavior

Resized when reset in react-hook-form.
Can trigger resize.

## Is this a breaking change (Yes/No): No

### CODE REVIEW

**Review by taroj1205 — COMMENTED** [review]
When using `type="reset"`, it does not resize automatically until focused.
```tsx
<Button type="reset" alignSelf="flex-end">
  Reset
</Button>
 ```
 

https://github.com/yamada-ui/yamada-ui/assets/61367823/3a294b5c-be72-42d1-b214-71254000d6c9

**Comment by 108yen** [comment]
@taroj1205 
I could not find a good solution.
I have implemented a function to trigger resize, so let's have them use this function.

**Comment by 108yen** [comment]
@taroj1205 
Please Approve.

**Review by taroj1205 — APPROVED** [review]
Approved

**Pull request merged**
