### PR TITLE
fix: added displayName and __ui__ to table components

### LINKED ISSUE #2908: `displayName` is not set for the component of "@yamada-ui/table"
script: component-display-name
package: @yamada-ui/table

### Description
The component "@yamada-ui/table" uses `forwardRef`, but `displayName` is not set, making it difficult to see the display in [React Developer Tools](https://github.com/facebook/react/tree/main/packages/react-devtools).

### Additional Information
Set `displayName` and `__ui__` after each component definition.

For example, like this.

```tsx
const Component = forwardRef((props, ref) => {
  ...
})

Component.displayName = 'Component'
Component.__ui__ = 'Component'
```

Replace `'component'` with the name of the component. For example, for a `Select` component, it is `'Select'`.

`__ui__` is an identifier required for internal use by Yamada UI. Be sure to set it together with `displayName`.

### PR DESCRIPTION
**Pull request by seferovich**
Closes #2908 

## Description

added displayName and __ui__ to table components

## Is this a breaking change (Yes/No):

no

### CODE REVIEW

**Review by illionillion — CHANGES_REQUESTED** [review]
@seferovich 

`thead`・`tbody`・`tfoot`

Please these components should also be marked with `displayName` and `__ui__`.

To do this, the component must be typed `FC`.
Also, the `FC` type must be imported from `@yamada-ui/core`.

**Comment by seferovich** [comment]
@illionillion 

When I try to add the type of `FC` from `@yamada-ui/core` to any of the components , I can't because it says that FC can't be imported because it doesn't exist. What should I do?

**Comment by illionillion** [comment]
> @illionillion
> 
> When I try to add the type of `FC` from `@yamada-ui/core` to any of the components , I can't because it says that FC can't be imported because it doesn't exist. What should I do?
> 
> Edit: Should I import it from`react`, since I saw that in the other components it's done like that?

@seferovich 

Please import FC from @yamada-ui/core since `__ui__` cannot be specified in react FC.
To import, merge the latest commit into your branch.
If this does not help, please reload the type that restarted VSCode's TS server.

**Comment by illionillion** [comment]
> > @illionillion
> > When I try to add the type of `FC` from `@yamada-ui/core` to any of the components , I can't because it says that FC can't be imported because it doesn't exist. What should I do?
> > Edit: Should I import it from`react`, since I saw that in the other components it's done like that?
> 
> @seferovich
> 
> Please import FC from @yamada-ui/core since `__ui__` cannot be specified in react FC. To import, merge the latest commit into your branch. If this does not help, please reload the type that restarted VSCode's TS server.

Sync fork to bring the main branch up to date and merge it into the branch you are working on.

image

**Comment by seferovich** [comment]
@illionillion 

I've done everything and eveything works now, just one small problem.

In `thead.tsx`, `FC` was already imported from `react` for the `SortIcon` component. 

Should I just import it like this, for example `import { FC as yamadaFC } from "@yamada-ui/core"` or do something else?

I'm really sorry for bothering and because this is taking too long, it's my second PR ever.

**Comment by illionillion** [comment]
@seferovich 

If there is a conflict between `react`'s `FC` and `@yamada-ui/core`'s `FC`, please use `@yamada-ui/core`'s `FC`

**Review by hirotomoyamada — APPROVED** [review]

**Comment by hirotomoyamada** [comment]
Thanks!

**Review by hirotomoyamada — CHANGES_REQUESTED** [review]
Please check [here](https://github.com/yamada-ui/yamada-ui/actions/runs/11075359966/job/30776134772?pr=2940)

**Comment by seferovich** [comment]
@hirotomoyamada 

I moved the imports to the top.

**Review by hirotomoyamada — APPROVED** [review]

**Comment by seferovich** [comment]
@illionillion
@hirotomoyamada 

Thank you very much for being patient with me. I'm sorry because it took so long.


Wish you all the best!

**Pull request merged**
