### PR TITLE
feat: Rename Divider to Separator

### PR DESCRIPTION
**Pull request by tskxz**
Closes https://github.com/yamada-ui/yamada-ui/issues/3292

As referred to in issue https://github.com/yamada-ui/yamada-ui/issues/3292 I renamed Divider to Separator. I redid the pull request, now it includes changelog and the target branch is v2.0.

### CODE REVIEW

**Review by 108yen — CHANGES_REQUESTED** [review]
Thanks for the correction!

Please run `pnpm docs:lint --fix`.

**Review by 108yen — DISMISSED** [review]

**Review by hirotomoyamada — CHANGES_REQUESTED** [review]
Documentation should be created in a separate PR.This will reflect in the documentation when it is imported.

**Review by hirotomoyamada — CHANGES_REQUESTED** [review]
Do not include changes to the `docs` folder in this PR.

**Comment by hirotomoyamada** [comment]
@tskxz

Hi, Thanks for the PR!

A week has passed since this PR was created, so maintainers will be joining this PR.

**Pull request closed without merging**
